controller_manager:
  ros__parameters:
    update_rate: 100 # Hz, same below

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters: #i think this like tells what the gui controller to do
    joints:
      - left_hip_joint
      - right_hip_joint
      - left_knee_joint
      - right_knee_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 50.0
    action_monitor_rate: 20.0
